export const CHANGE_DURATION = 'CHANGE_DURATION';
export const CHANGE_INTEREST = 'CHANGE_INTEREST';
export const CHANGE_TOTALLOAN = 'CHANGE_TOTALLOAN';
export const DATA_POINTS_RECIEVED = 'DATA_POINTS_RECIEVED';
